plugins {
    id 'java-library'
    id 'maven-publish'
}

group = 'org.example'
version = '1.0-SNAPSHOT'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

repositories {
    mavenCentral()
}

dependencies {
    // Lombok
    def lombokVersion = "1.18.34"

    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
    testCompileOnly "org.projectlombok:lombok:${lombokVersion}"
    testAnnotationProcessor "org.projectlombok:lombok:${lombokVersion}"
}

publishing {
    publications {
        maven(MavenPublication) {
            groupId = project.group
            artifactId = 'message'
            version = project.version
            from components.java
        }
    }
}